version: '3.9'

services:
  pricing-api:
    container_name: pricing-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
      APP_ENV: prod
      APP_REGION: es
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      PRICING_REDIS_TTL_SECONDS: 600
    depends_on:
      - redis
    networks:
      - pricing-net

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pricing-net

networks:
  pricing-net:
    driver: bridge
