CREATE TABLE IF NOT EXISTS PRICES (
    ID BIGINT PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY BIGINT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prices_query
ON PRICES (PRODUCT_ID, BRAND_ID, START_DATE, END_DATE);
